### PR TITLE
Support conditionally importing Google Fonts

### PR DESCRIPTION
**Pull request by technicalpickles**
This already uses a variable, so this change checks that it's true. This allows users to set `$web-font-path: false`, which will skip it. This is helpful for times when users want better control over google web fonts loading, like if they are using webpack, want to pre-load it, etc

My specific use case: I'm using `@beyonk/google-fonts-webpack-plugin` to generate a fonts.css, and then add that to an html generated by `html-webpack-plugin`. By disabling the `@import`, I'm able to serve up local fonts, and avoid a flash of unstyled text.

---

I did try running `grunt swatch`, but it ended up removing the conditionals in 5 of the themes 🤔

### CODE REVIEW

**Comment by technicalpickles** [comment]
I think this would help a number of previous issues that have come up, assuming they are using sass:

- https://github.com/thomaspark/bootswatch/issues/711
- https://github.com/thomaspark/bootswatch/issues/47
- https://github.com/thomaspark/bootswatch/issues/573
- https://github.com/thomaspark/bootswatch/issues/47

**Comment by thomaspark** [comment]
Hey @technicalpickles, thanks for the PR. It's looking good.

You missed a couple of v4 files, at:
* `dist/solar/_bootswatch.scss`
* `dist/superhero/_bootswatch.scss`

Also if you wanna add this to v3, you should make the changes in `dist/3/**/` and run `grunt:swatch` to copy them over to `docs/`.

Other than that it's ready to go.

**Comment by technicalpickles** [comment]
> Also if you wanna add this to v3, you should make the changes in `dist/3/**/` and run `grunt:swatch` to copy them over to `docs/`.

I'm not seeing a `dist/3` directory 🤔  What decides how to where to copy into `docs`, ie  `docs/3`, `docs/4` etc?

**Comment by thomaspark** [comment]
Oops, for earlier versions `docs/` is sufficient. This is perfect.

**Comment by thomaspark** [comment]
Unfortunately we'll have to wait for the next bump from Bootstrap to release a new version, since we keep version numbers in sync.

**Comment by rawnsley** [comment]
Myself and at least one other person had a problem with this code ([as described here](https://stackoverflow.com/a/77266455/671393)) and I wondered if anyone with a better understanding of SCSS had any insights.

**Pull request merged**
