### PR TITLE
Update bootstrap to v4.0.0

### PR DESCRIPTION
**Pull request by m5o**
* `npm update bootstrap`
* genarate `grunt swatch`
* update version in `api/4.json`
* update files `docs/_vendor/bootstrap/dist`

/cc @mkhairi @XhmikosR

### CODE REVIEW

**Comment by thomaspark** [comment]
@m5o thank you. Exciting to hit 4.0.0 final!

**Comment by nickmccurdy** [comment]
Thank you for doing this so quickly! I'm excited to try out the stable release.

**Comment by m5o** [comment]
🔔 @mkhairi Don't forget to update [bootswatch-sass rubygems](https://rubygems.org/gems/bootswatch)

**Comment by m5o** [comment]
🙄 @XhmikosR Are you in charge updating https://www.bootstrapcdn.com/bootswatch/ ?

**Comment by XhmikosR** [comment]
@m5o no need to ask me the same thing each release. Yes, I am, but make an issue there. Also, remember, there's real life stuff, so you know.

**Comment by m5o** [comment]
Sorry, did’t know maxcdn is organized in a public org/repo. ✌️ Thanks for your support!

**Pull request merged**
