### PR TITLE
materia use input variables

### PR DESCRIPTION
**Pull request by m5o**
* use input variables
* remove custom resets
* remove custom radio and checkbox styles
  * use `$custom-checkbox-*`
* fix issues materia usage with [custom floating-labels](http://getbootstrap.com/docs/4.0/examples/floating-labels/)

screen shot 2018-03-22 at 21 52 03

### CODE REVIEW

**Comment by thomaspark** [comment]
Hey @m5o, love the changes you're making here. Can you ping me when the PR is ready for review?

**Comment by m5o** [comment]
I'm done with the refinements, please review 😉

**Comment by thomaspark** [comment]
Hey @m5o, spotted one issue: you can toggle the checkboxes/radios by clicking the labels, but not clicking the inputs directly. Otherwise looks good to go.

**Comment by m5o** [comment]
@thomaspark done with https://github.com/thomaspark/bootswatch/pull/810/commits/bb3a493dbd81436f311452082cb0d430e70c8f63

**Comment by thomaspark** [comment]
Looks good, thanks for your efforts @m5o!

**Pull request merged**
