### PR TITLE
Cosmetic design for smartphones

### PR DESCRIPTION
**Pull request by alain01**
Just cosmetic design for smartphone.

See the problem:
Capture d’écran 2021-08-17 220844
Capture d’écran 2021-08-17 220906
Capture d’écran 2021-08-17 220950

This PR modify the main page and only the cerulean page.
We need to modify other pages but I dont know if "mb-1" suits you.

Alain

### CODE REVIEW

**Comment by thomaspark** [comment]
Hey @alain01, thanks for the suggestion. I agree this improves the style on mobile.

Instead of adding `mb-1` classes, how about we add something like the following to `_assets/scss/custom.scss`?

```css
.bs-component > .btn,
.bs-component > .btn-group,
#home .section-preview .card .btn-group {
    margin-bottom: .25rem;
}
```

**Comment by alain01** [comment]
Sure, much much better !

**Comment by nightw0lv** [comment]
best way to use this themes and make them as you like is only logic to override them according to your needs with a custom file is only logic so you can have the updates and not a mess, but good catch on mobiles!

**Comment by alain01** [comment]
Hum, im not familiar with scss.
I added your code to _assets/scss/custom.scss 
and convert with "Scout-App" but I see differences between the initial custom.min.css and the generated file (except the added elements, of course) by the application.

It's locacated at 2 points : 
your file:
`.dropdown-menu.show[aria-labelledby="themes"]{display:-ms-flexbox;display:flex;width:420px;-ms-flex-wrap:wrap;flex-wrap:wrap;`
The Scout file:
`.dropdown-menu.show[aria-labelledby="themes"]{display:flex;width:420px;flex-wrap:wrap;`

and here:
your file:
`.section-tout .icon{display:-ms-flexbox;display:flex;-ms-flex-pack:center;justify-content:center;-ms-flex-align:center;align-items:center;`
The Scout file:
`.section-tout .icon{display:flex;justify-content:center;align-items:center;`

Sorry if it's a stupid remark.

**Comment by thomaspark** [comment]
Looks like minor differences in browser support in the tools we're using to build the CSS. I should have this as a built-in task rather than relying on external tools.

Feel free to manually change the CSS at those 2 points to match the old file and submit the PR. Or I can take care of this issue.

**Comment by alain01** [comment]
Ok, I changed my PR.
Please check all ;-)

**Comment by thomaspark** [comment]
Looks good. Could you just change the indent in your scss file to 2 spaces to pass the test. Then I'll merge it in.

**Comment by alain01** [comment]
Humm, sorry,
I hope it's ok now...

**Pull request merged**
