### PR TITLE
Update flaty/bootswatch.less, imported variables.less file and add .box-shadow() which was undefined before

### PR DESCRIPTION
**Pull request by carlton64**
updating flatly/bootswatch.less file due to encountering errors

### CODE REVIEW

**Comment by thomaspark** [comment]
Hey @carlton64, if you follow the directions here, you don't need to add `.box-shadow()` or any other mixin as it will pull in the Bootstrap source:

https://bootswatch.com/help/

**Comment by carlton64** [comment]
Oh sorry my bad, I apologise for the disturbance and thank you.

________________________________

**Comment by thomaspark** [comment]
No worries, let me know if you spot anything else!

**Comment by carlton64** [comment]
Yeah sure definitely will.

________________________________

**Pull request closed without merging**
