### PR TITLE
[Paper theme] Ensured consistency between button[disabled] and a.disabled

### PR DESCRIPTION
**Pull request by hungryzi**
I'm using the Paper theme and noticed some inconsistency between `button[disabled]` and `a.disabled`. 

I've added examples to show it:

screen shot 2016-11-05 at 8 58 51 pm

This PR aims to fix those inconsistencies. There is still inconsistency in `cursor` but that's also the case with the default Bootstrap 3 so I decided to leave it that way.

### CODE REVIEW

**Comment by thomaspark** [comment]
Hey @hungryzi , thanks for catching this and submitting a fix. Can you just drop the changes to `paper/index.html` from the PR?

**Comment by hungryzi** [comment]
May I know why? I find it's easier to debug if the demo page includes both usages (`a.disabled` and `button[disabled]`).

**Comment by thomaspark** [comment]
`index.html` is meant to preview the theme, not necessarily be comprehensive for testing. For that there's `tests/components.html`. If some change were made to `index.html`, it should also be made for all of the themes.

**Comment by hungryzi** [comment]
@thomaspark That makes sense. Thanks for explaining. I've reverted that commit.

**Comment by thomaspark** [comment]
Thanks again for your fix!

**Pull request merged**
