### PR TITLE
Improve inline SVGs

### PR DESCRIPTION
**Pull request by XhmikosR**
* optimize them with the latest SVGO
* use Bootstrap's `escape-svg` function
* remove `width` and `height` attributes
* use the color variables when possible

TODO:

- [x] `width` and `height` can probably be removed too, but please verify
- [ ] move these to variables later

### CODE REVIEW

**Comment by XhmikosR** [comment]
@thomaspark apart from the TODO (please check them out :) ), it will be better if you overwrote the Bootstrap's variables when possible for the icons in all themes. This way you won't get duplicate selectors which increases the CSS size a lot right now. And you probably won't need to use `escape-svg()` if those variables are escaped upstream.

**Comment by thomaspark** [comment]
Thanks @XhmikosR... I don't think I was able to make use of Bootstrap variables last time I took a shot at this, but I'll take another look at it.

**Comment by XhmikosR** [comment]
Something I forgot to clarify; if you backport these changes to v4, make sure you keep width and height attributes because at least IE needed them IIRC.

**Comment by XhmikosR** [comment]
@thomaspark I'd say you should start with first moving those to your variables file so that they can be overwritten. You will still need to use `escape-svg` but it should be cleaner.

Then you need to identify if these icons already have variables upstream that fit your needs. This will be the ideal solution because you won't output duplicate stuff which cost size a lot since they are SVGs.

**Comment by thomaspark** [comment]
> if you backport these changes to v4, make sure you keep width and height attributes because at least IE needed them IIRC.

TIL. Thanks for the tips!

**Comment by XhmikosR** [comment]
Yeah, we hit this in v4 for sure at some point so better play it safe. That being said, I haven't tried Bootswatch v4.6.1 on IE. If you have a browserstack account you could test it at least with IE 11 yourself.

**Pull request merged**
