### PR TITLE
Use display=swap for Google Font performance

### PR DESCRIPTION
**Pull request by blimmer**
First of all, I want to sincerely thank you for this project. I've been using the beautiful Journal theme for my website for some time, and I love it.

I noticed that Google PageSpeed Insights have recently been recommending using the `display=swap` parameter when loading up remote Google Fonts.

Screen Shot 2020-01-30 at 5 21 54 PM

The "learn more" link goes [here](https://web.dev/font-display) and explains how this parameter helps to avoid the FOIT (Flash of Invisible Text) issue present on some browsers.

Interestingly, the Google Fonts web experience now includes this parameter by default.

Screen Shot 2020-01-30 at 5 22 00 PM

So, this PR adds the query parameter to all fonts used in this project.

### CODE REVIEW

**Comment by thomaspark** [comment]
Hey @blimmer, thanks for the PR, agree we should keep up with Google Font guidelines if we are to use them.

It looks like this adds the param for v3 but not v4. They'd have to be made in `_bootswatch.scss` for relevant themes under `dist/` and build re-run.

**Comment by blimmer** [comment]
Thanks for the guidance! I think I've made the changes requested. Please have a look when you have a second.

**Comment by thomaspark** [comment]
This is looking good. I found one more missed spot, the minified css files under `docs/3/`. Once those are changed it should be ready for merge!

**Comment by blimmer** [comment]
Ah, sorry about that. I was explicitly excluding `*.min.css` because I thought those would be automatically regenerated with the build. I've got those updated now.

**Comment by thomaspark** [comment]
Ah I see, `/3/` doesn't get touched by the root build commands, but it does have its own grunt file in its directory to regenerate them.

The v3 `min` files look good now, but it looks like the other css/scss/less files in v3 got the `&display=swap` duplicated in the process.

**Comment by blimmer** [comment]
Sigh, I'm sorry. I haven't dug properly on how this whole project works / is built and am moving too fast. I've just re-reviewed and I think this is finally right. Thanks for your patience.

**Comment by thomaspark** [comment]
👍 Looks good to me. Thanks for seeing this thru!

**Pull request merged**
