### PR TITLE
Add solorized to composer.json

### PR DESCRIPTION
**Pull request by kadimi**

### CODE REVIEW

**Comment by thomaspark** [comment]
Overlooked this, thanks @kadimi!

**Comment by kadimi** [comment]
@thomaspark Kindly tag v3.3.8, `composer install` still uses v3.3.7.

Thanks
Nabil

**Comment by thomaspark** [comment]
We stay synced with Bootstrap, so unfortunately can't go to v3.3.8 until they do.

**Comment by kadimi** [comment]
That makes sence. Thanks.

**Comment by kadimi** [comment]
@thomaspark On a second thought, maybe you can delete the old tag and tag again.

**Pull request merged**
