### PR TITLE
Update Bootstrap v4 & fix compile

### PR DESCRIPTION
**Pull request by jonnysp**

### CODE REVIEW

**Comment by thomaspark** [comment]
Can you give a rundown of what you changed? Lots of changes but Bootstrap hasn't had a new release from v4.0.0-alpha.6. Thanks.

**Comment by jonnysp** [comment]
the current dev state of Bootstrap. and in your variables the spacers map.

**Comment by thomaspark** [comment]
Ah, let's wait to update until v4.0.0-alpha.7 or beta if it's next.

**Comment by jipexu** [comment]
beta will be next ...

**Comment by thomaspark** [comment]
Will push the next update for that.

**Pull request closed without merging**
