### PR TITLE
Enable sourcemaps.

### PR DESCRIPTION
**Pull request by XhmikosR**
It seems to work after all :)

The only issue is a bug with clean-css and path separators on Windows, but assuming you always build on the same platform the sourcemaps will be consistent and fine.

Draft because I'd like to get #1001 merged first.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@thomaspark this is ready for testing. Do note that I didn't commit the map files myself due to that Windows issue, but I can do it tomorrow from my Linux machine.

**Comment by XhmikosR** [comment]
@thomaspark I played with this more and it seems sourcemaps are wrong. I will remove them for now and see if I can make them work properly later.

**Comment by XhmikosR** [comment]
Actually, wait. clean-css's sourcemaps are wrong only.

**Comment by XhmikosR** [comment]
How do you want to proceed? It's an issue with grunt-contrib-cssmin, it doesn't expose the option to inline the sourcemap sources.

Not sure if it makes sense to keep the map files only for the unminified files since map files are mostly useful with minified files.

**Comment by XhmikosR** [comment]
Damn it, I think we are just missing an option. I'll make a PR, sorry for the noise.

**Comment by thomaspark** [comment]
I'm just glad it ended up an easy fix. 😀

**Pull request merged**
