### PR TITLE
Discard some change for #628

### PR DESCRIPTION
**Pull request by zcyzcy88**

### CODE REVIEW

**Comment by thomaspark** [comment]
Can you keep PR limited just to border radius and transition changes? Please remove all other changes including those to index.html and box-shadow. Thanks!

**Comment by zcyzcy88** [comment]
Updated.

**Comment by thomaspark** [comment]
Thanks, but there's still some unrelated changes remaining in the PR that should be reverted, like the removal of `a` and `.table-hover` transitions, and `.close` styles.

**Comment by zcyzcy88** [comment]
Updated.
Sorry for the confusing Git commit history. I am not good at using Git.

**Pull request closed without merging**
