### PR TITLE
Added material checkbox and radio buttons #393

### PR DESCRIPTION
**Pull request by ryanwalters**
http://ryanwalters.github.io/bootswatch/paper/

Working in Chrome right now. Should give you a good starting point for trying to port over to other browsers.

Here is a fiddle with the other states:
http://jsfiddle.net/RyanWalters/0qr4htdg/

### CODE REVIEW

**Comment by nahtnam** [comment]
Shouldnt it have a circle around it?

http://www.google.com/design/spec/components/switches.html#switches-checkbox

**Comment by ryanwalters** [comment]
Those are the ink ripples, I don't know if they want those implemented as well, at least not automatically.

**Comment by nahtnam** [comment]
Oh ok. I didnt realize that.

Thanks.

**Comment by thomaspark** [comment]
This looks fantastic! Definitely gonna end up in Paper. Thanks @ryanwalters.

Even if they're in the design guidelines, I'm ambivalent about the ink ripples. They eat a lot of space, and seem like visual overkill for anything but mobile. But additional markup would definitely rule it out.

**Pull request closed without merging**
