### PR TITLE
Gruntfile.js: further cleanup

### PR DESCRIPTION
**Pull request by XhmikosR**
Also add a `docs-css` task

### CODE REVIEW

**Comment by XhmikosR** [comment]
Only thing left is to clear up the "build" and "swatch" tasks, maybe change their description. And then I'll add the scripts in npm too. I believe this is as good as it gets considering the age of the build system, but it does its job fine now. :)

**Comment by thomaspark** [comment]
These changes are great, thanks @XhmikosR!

**Comment by XhmikosR** [comment]
@thomaspark I don't want to make a new issue but here's my current local TODO:

* be explicit with the transitioned properties
* don't use background if background-color is meant to be used
* specify { cascade: false } for autoprefixer

* auto-deploy from gh-pages on tags
* use the minified CSS in v4 docs
* add image dimensions in index page
* add loading="lazy" in index page images
* move iframe border property to custom.scss
* fix accessibility markup
* lint custom.js
* add ESLint

Feel free to drop by our https://bootstrap-slack.herokuapp.com/ and send me a DM. Also, if you can tackle any of the above that would be perfect. BTW, when do you plan to cut a new release? We don't have a plan for a new 4.x release soon.

**Comment by thomaspark** [comment]
Hey @XhmikosR, I'll grab some of these todos and open issues for em so we don't overlap our efforts.

Once the dust settles from all the PRs I'll cut a new release. Seems like only a couple of these todos will affect the themes so will prioritize those first.

**Pull request merged**
