### PR TITLE
Update bootstrap to v4.0.0 beta.3

### LINKED ISSUE #764: Update to 4.0.0-beta.3
Would be great to see an update to Bootstrap 4 Beta 3

### PR DESCRIPTION
**Pull request by m5o**
* `npm update bootstrap`
* `npm update popper.js@1.12.9`
* genarate `grunt swatch`
* update version in `api/4.json`
* update files `docs/_vendor/[bootstrap|popper.js]/dist`
* update input-group markup
* update custom-control markup

Closes #764

### CODE REVIEW

**Comment by thomaspark** [comment]
Hey @m5o, awesome job on this update, thanks. Looks like you threw in some minor fixes like switching from `px` to `rem` and adding a missing `!default` flag too. All of it looks good to go!

**Comment by XhmikosR** [comment]
@thomaspark: can you CC me when you release this so that update BootstrapCDN?

**Comment by m5o** [comment]
@XhmikosR 
I've collected tasks for Thomas in this issue https://github.com/thomaspark/bootswatch/issues/766

**Comment by XhmikosR** [comment]
Thanks, I subscribed to the issue.

**Comment by thomaspark** [comment]
Hey @XhmikosR, Beta 3 is tagged now!

https://github.com/thomaspark/bootswatch/releases/tag/v4.0.0-beta.3

**Comment by XhmikosR** [comment]
Thanks!

**Pull request merged**
