### PR TITLE
fix white-on-white custom-file-label on superhero

### PR DESCRIPTION
**Pull request by lifeofguenter**
This will fix a "white-on-white" label: https://getbootstrap.com/docs/4.1/components/forms/#file-browser

### CODE REVIEW

**Comment by thomaspark** [comment]
Hey @lifeofguenter, thanks for the pull request. Can you post a demo of this bug and what browser you're on? I'm not seeing it on my end.

screen shot 2018-07-30 at 2 35 33 pm

**Comment by thomaspark** [comment]
I see, thanks. Can you make the change to the scss files in the `dist` directory instead of the css directly, then run `grunt swatch:superhero` to build the rest of the files? Or let me know if you want me to take care of it.

Adding the following to `dist/superhero/_variables.scss` in the forms section should do the trick:

```scss
$custom-file-color:                 $white !default;
```

**Comment by lifeofguenter** [comment]
Awesome, thanks @thomaspark for the hint - I have no clue of frontend unfortunately :)

I updated the `_variables.scss`, seems like I had to just remove the variable for the bootstrap default to take-over, but still overwrite `$custom-file-button-color` to white so the button will look properly.

Most of the changes seem to be whitespaces only.

**Comment by thomaspark** [comment]
Thanks, it looks good to go!

**Pull request merged**
