### PR TITLE
Paper: Improved material style button hover/click animation, swatch update

### PR DESCRIPTION
**Pull request by homerjam**
Hi,

I played around with the button appearance/behaviour a little - I think its closer to "the real deal" now, see what you think.

Keep up the great work

### CODE REVIEW

**Comment by homerjam** [comment]
Let me know if I should build this - `grunt build_scss` right?

**Comment by thomaspark** [comment]
Hey @homerjam, any reason you closed this PR? Wanted to check it out, just finding the time now.

**Comment by homerjam** [comment]
Hey,

Mainly because I wasn't happy with it - I've improved it now so will try and open another. The thing is I've realised there is a bit of variation between the Google design guidelines and the Polymer project - yours follows the guidelines whereas my changes are a little more like the Polymer project. It might be overkill but perhaps even another theme would be good so the two could live in parallel. Anyway will let you decide when I've been able to upload my changes.

**Comment by thomaspark** [comment]
Cool, thanks. Yeah, the two references diverge quite a bit, so I've been using them as general guides instead of specs. But I've tended to lean towards Google's ref which I find more aesthetic.

**Comment by homerjam** [comment]
Have a butchers: http://homerjam.github.io/bootswatch/paper/

**Comment by thomaspark** [comment]
Cool. Will stick with the current palette, but this is a good representation of the Polymer version. Round buttons are also a nice touch. We kicked that around as a Papers Plus-like add-on in #303.

**Comment by homerjam** [comment]
Absolutely, that'll always remain subjective. I like the idea of addons but would be keen to avoid js as I mentioned in the other thread. If you could figure out a less/scss only setup that'd be great.

Otherwise maybe a wiki/FAQ/readme that listed forks like mine for reference - could be useful for others?

Anyways, great project.

**Pull request closed without merging**
