### PR TITLE
docs: remove jQuery and refactor code

### LINKED ISSUE #1145: v5 docs: remove jQuery

### PR DESCRIPTION
**Pull request by XhmikosR**
Requires #1157. Fixes #1145.

@thomaspark have you thought about adding Netlify for PR previews? If you need help I can help out.

### CODE REVIEW

**Comment by XhmikosR** [comment]
This needs careful review and having PR previews would really help. I also simplified the code, hopefully I understood the original one properly :)

**Comment by thomaspark** [comment]
Hey @XhmikosR, help with getting PR previews set up would be very welcome.

**Comment by XhmikosR** [comment]
Ping me on Slack and we'll set it up :) I should have a little time in about 5-6 hours from now.

**Comment by XhmikosR** [comment]
Friendly ping @thomaspark ^^

**Comment by thomaspark** [comment]
Thanks for the reminder @XhmikosR!

**Comment by XhmikosR** [comment]
@thomaspark manual preview of the current v5 branch until you set up Netlify: https://dazzling-perlman-39c8a7.netlify.app

PS:

1. it's still worth looking into inlining splash.svg in the HTML
2. might also be worth switching to Bootstrap Icons instead of Font Awesome :)

**Comment by thomaspark** [comment]
Thanks, I need to get on that...

1. Sounds good.
2. Agree 100%!!!

**Pull request merged**
