### PR TITLE
paper: fade effect for table-hover

### LINKED ISSUE #444: [Paper] Fade Effect For table-hover
Feature request, implement the nice fade transition for `table-hover` rows. The same effect that happens for buttons, etc.

### PR DESCRIPTION
**Pull request by Panman8201**
Used the same `.transition()` that other elements use, like .btn’s.
Simply added the transition for both .less and .scss then ran `grunt
swatch:paper`. Closes #444

### CODE REVIEW

**Comment by Panman8201** [comment]
Also, this I used the same selector that bootstrap uses: https://github.com/twbs/bootstrap/blob/71f4abc2015164de45eb83c9b63ac739efd15a4d/less/tables.less#L126

**Comment by thomaspark** [comment]
Thanks, I like the idea of having transitions on table hover.

This PR works with plain table rows, but not if they've had a state like `success` applied to it.

**Comment by Panman8201** [comment]
Looks like contextual classes apply the background color to the `td` directly, rather than the `tr`. Should be able to apply the same transition to td as well, but I'll look at any drawbacks.

Working on a server issue ATM so it might not be today yet.

**Comment by Panman8201** [comment]
Alright, I've added selectors for the contextual classes, the same way bootstrap applies the background styles.

**Comment by Panman8201** [comment]
@thomaspark did you need anything else with this PR? I have another quick fade thing for `.close` links but didn't create a branch for this PR, so I have to wait until it's merged (or not).

**Comment by thomaspark** [comment]
Hi @Panman8201, this looks good to go. Thanks for the changes (and squashing!). I'll merge now.

**Pull request merged**
